### ISSUE TITLE
Documentation for config.zip

### ISSUE THREAD

**Issue by rfratto** [adplabs/adp-core-node#5]
[This page](https://github.com/adplabs/adp-core-node/blob/master/docs/README.md) references a `config.zip` file to be passed to `consumerApplicationInstance`. 

What is expected to exist in the .zip file (or do developers obtain one from ADP)? I see that two `config.zip`s exist in the unit tests, but it's not clear how to utilize them or what would be in a `config.zip` for a production application.

**Comment by ginomarotta-adp** [comment]
The config.zip file contains schema definitions that allow the adp-core-node library to properly format requests to the ADP API backend.  Each one is tailor made to the specific app and will be delivered by your ADP representative.

**Comment by rfratto** [comment]
Got it, thanks!
